import os
import glob
import numpy as np
import open3d as o3d
import argparse
from scipy.spatial.transform import Rotation as R
import time

# Camera intrinsics for 512x512 and FOV=90 (assignment spec)
IMG_W, IMG_H = 512, 512
FOV = np.deg2rad(90.0)
FX = (IMG_W / 2.0) / np.tan(FOV / 2.0)
FY = (IMG_H / 2.0) / np.tan(FOV / 2.0)
CX, CY = IMG_W / 2.0, IMG_H / 2.0
DEPTH_SCALE = 1000.0


def depth_image_to_point_cloud(rgb_image, depth_image):
    """Task 1: unproject RGB-D image to colored point cloud."""
    rgb = np.asarray(rgb_image, dtype=np.float32)
    depth = np.asarray(depth_image)

    if depth.shape[0] != IMG_H or depth.shape[1] != IMG_W:
        raise ValueError(f"Expected depth size {(IMG_H, IMG_W)}, got {depth.shape[:2]}")

    # Support both uint16(mm) and uint8 depth generated by load.py visualization conversion.
    if depth.dtype == np.uint16 or np.max(depth) > 255:
        z = depth.astype(np.float32) / DEPTH_SCALE
    else:
        z = (depth.astype(np.float32) / 255.0) * 10.0

    u, v = np.meshgrid(np.arange(IMG_W), np.arange(IMG_H))
    valid = (z > 0.05) & (z < 10.0)

    z = z[valid]
    u = u[valid]
    v = v[valid]

    x = (u - CX) * z / FX
    y = (v - CY) * z / FY

    points_3d = np.stack([x, y, z], axis=1)
    colors_norm = rgb[valid] / 255.0

    pcd = o3d.geometry.PointCloud()
    pcd.points = o3d.utility.Vector3dVector(points_3d)
    pcd.colors = o3d.utility.Vector3dVector(colors_norm)
    return pcd


def preprocess_point_cloud(pcd, voxel_size):
    """Voxel downsample + normal estimation + FPFH."""
    pcd_down = pcd.voxel_down_sample(voxel_size)

    radius_normal = voxel_size * 2.0
    pcd_down.estimate_normals(
        o3d.geometry.KDTreeSearchParamHybrid(radius=radius_normal, max_nn=30)
    )

    radius_feature = voxel_size * 5.0
    pcd_fpfh = o3d.pipelines.registration.compute_fpfh_feature(
        pcd_down,
        o3d.geometry.KDTreeSearchParamHybrid(radius=radius_feature, max_nn=100)
    )
    return pcd_down, pcd_fpfh


def local_icp_algorithm(source_down, target_down, trans_init, threshold):
    """Task 2 (required): Open3D Point-to-Plane ICP."""
    return o3d.pipelines.registration.registration_icp(
        source_down,
        target_down,
        threshold,
        trans_init,
        o3d.pipelines.registration.TransformationEstimationPointToPlane(),
        o3d.pipelines.registration.ICPConvergenceCriteria(max_iteration=50),
    )


def is_reasonable_transform(T, max_translation=0.7, max_rotation_deg=60.0):
    """Reject catastrophic frame-to-frame jumps."""
    t = np.linalg.norm(T[:3, 3])
    rot = R.from_matrix(T[:3, :3]).magnitude() * (180.0 / np.pi)
    return t <= max_translation and rot <= max_rotation_deg


def visualize_and_evaluate(reconstructed_pcd, predicted_cam_poses, gt_poses, args):
    """Task 3: draw trajectories and compute Mean L2 position error."""
    pred = np.asarray(predicted_cam_poses)
    pred_xyz = pred[:, :3, 3]

    geos = [reconstructed_pcd]

    pred_lines = [[i, i + 1] for i in range(len(pred_xyz) - 1)]
    pred_ls = o3d.geometry.LineSet(
        points=o3d.utility.Vector3dVector(pred_xyz),
        lines=o3d.utility.Vector2iVector(pred_lines),
    )
    pred_ls.colors = o3d.utility.Vector3dVector(
        np.tile(np.array([[1.0, 0.0, 0.0]]), (len(pred_lines), 1))
    )
    geos.append(pred_ls)

    mean_l2_error = float("nan")
    if gt_poses is not None and len(gt_poses) > 0:
        gt_xyz = gt_poses[:, :3, 3]
        n = min(len(gt_xyz), len(pred_xyz))
        gt_xyz = gt_xyz[:n]
        pred_xyz_eval = pred_xyz[:n]

        gt_lines = [[i, i + 1] for i in range(len(gt_xyz) - 1)]
        gt_ls = o3d.geometry.LineSet(
            points=o3d.utility.Vector3dVector(gt_xyz),
            lines=o3d.utility.Vector2iVector(gt_lines),
        )
        gt_ls.colors = o3d.utility.Vector3dVector(
            np.tile(np.array([[0.0, 0.0, 0.0]]), (len(gt_lines), 1))
        )
        geos.append(gt_ls)

        mean_l2_error = np.mean(np.linalg.norm(pred_xyz_eval - gt_xyz, axis=1))

    print(f"Mean L2 distance: {mean_l2_error:.6f} meters")

    o3d.visualization.draw_geometries(
        geos,
        window_name=f"Floor {args.floor} Reconstruction"
    )
    return mean_l2_error


def reconstruct(args):
    voxel_size = 0.12
    rgb_dir = os.path.join(args.data_root, "rgb")
    depth_dir = os.path.join(args.data_root, "depth")

    rgb_files = sorted(
        glob.glob(os.path.join(rgb_dir, "*.png")),
        key=lambda p: int(os.path.splitext(os.path.basename(p))[0]),
    )
    depth_files = sorted(
        glob.glob(os.path.join(depth_dir, "*.png")),
        key=lambda p: int(os.path.splitext(os.path.basename(p))[0]),
    )

    gt_pose_path = os.path.join(args.data_root, "GT_pose.npy")
    gt_poses = None
    if os.path.exists(gt_pose_path):
        gt_data = np.load(gt_pose_path)
        mats = []
        for p in gt_data:
            mat = np.eye(4)
            mat[:3, :3] = R.from_quat([p[4], p[5], p[6], p[3]]).as_matrix()
            mat[:3, 3] = [p[0], p[1], p[2]]
            mats.append(mat)
        gt_poses = np.stack(mats) if mats else None

    if len(rgb_files) == 0 or len(depth_files) == 0:
        return o3d.geometry.PointCloud(), [np.eye(4)], gt_poses

    camera_poses = [np.eye(4)]
    accumulated_pcd = o3d.geometry.PointCloud()

    first_rgb = o3d.io.read_image(rgb_files[0])
    first_depth = o3d.io.read_image(depth_files[0])
    first_pcd = depth_image_to_point_cloud(first_rgb, first_depth)
    accumulated_pcd += first_pcd

    for i in range(1, min(len(rgb_files), len(depth_files))):
        print(f"Processing Frame {i}...")

        rgb_prev = o3d.io.read_image(rgb_files[i - 1])
        depth_prev = o3d.io.read_image(depth_files[i - 1])
        rgb_curr = o3d.io.read_image(rgb_files[i])
        depth_curr = o3d.io.read_image(depth_files[i])

        source = depth_image_to_point_cloud(rgb_curr, depth_curr)
        target = depth_image_to_point_cloud(rgb_prev, depth_prev)

        source_down, source_fpfh = preprocess_point_cloud(source, voxel_size)
        target_down, target_fpfh = preprocess_point_cloud(target, voxel_size)

        distance_threshold = voxel_size * 2.0
        # RANSAC can become unstable on low-overlap frames. Use non-mutual matching
        # (fewer warnings) and fallback to identity init when global alignment is weak.
        if len(source_down.points) < 30 or len(target_down.points) < 30:
            ransac_init = np.eye(4)
        else:
            ransac_result = o3d.pipelines.registration.registration_ransac_based_on_feature_matching(
                source_down,
                target_down,
                source_fpfh,
                target_fpfh,
                mutual_filter=False,
                max_correspondence_distance=distance_threshold,
                estimation_method=o3d.pipelines.registration.TransformationEstimationPointToPoint(False),
                ransac_n=4,
                checkers=[
                    o3d.pipelines.registration.CorrespondenceCheckerBasedOnEdgeLength(0.9),
                    o3d.pipelines.registration.CorrespondenceCheckerBasedOnDistance(distance_threshold),
                ],
                criteria=o3d.pipelines.registration.RANSACConvergenceCriteria(50000, 0.999),
            )
            ransac_init = (
                ransac_result.transformation
                if (ransac_result.fitness > 0.05 and ransac_result.inlier_rmse < 0.2)
                else np.eye(4)
            )

        icp_result = local_icp_algorithm(
            source_down,
            target_down,
            ransac_init,
            distance_threshold,
        )

        T_curr_to_prev = icp_result.transformation
        if not is_reasonable_transform(T_curr_to_prev):
            # Bad registration can produce a single giant jump that ruins the map.
            # Fallback to no-motion for this frame to keep reconstruction stable.
            T_curr_to_prev = np.eye(4)

        T_prev_to_world = camera_poses[-1]
        T_curr_to_world = T_prev_to_world @ T_curr_to_prev
        camera_poses.append(T_curr_to_world)

        source_world = source.transform(T_curr_to_world.copy())
        accumulated_pcd += source_world

    # Remove ceiling: clip top 5% in Y for clearer visualization.
    points = np.asarray(accumulated_pcd.points)
    if len(points) > 0:
        y_thresh = np.percentile(points[:, 1], 95)
        keep_mask = points[:, 1] < y_thresh
        colors = np.asarray(accumulated_pcd.colors)
        accumulated_pcd = o3d.geometry.PointCloud()
        accumulated_pcd.points = o3d.utility.Vector3dVector(points[keep_mask])
        accumulated_pcd.colors = o3d.utility.Vector3dVector(colors[keep_mask])
        accumulated_pcd = accumulated_pcd.voxel_down_sample(voxel_size=0.03)

    return accumulated_pcd, camera_poses, gt_poses


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('-f', '--floor', type=int, default=1)
    args = parser.parse_args()

    args.data_root = "data_collection/first_floor/" if args.floor == 1 else "data_collection/second_floor/"

    start_time = time.time()
    result_pcd, pred_poses, gt_poses = reconstruct(args)

    print(f"Total execution time: {time.time() - start_time:.2f}s")
    visualize_and_evaluate(result_pcd, pred_poses, gt_poses, args)
